apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend-poll-app-jenkins-service
  labels:
    app: django-backend-poll-app-jenkins-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-backend-poll-app-jenkins-service
  template:
    metadata:
      labels:
        app: django-backend-poll-app-jenkins-service
    spec:
      containers:
      - name: django-poll-kube
        imagePullPolicy: Always
        image: gopalghule05/lnx_poll_prj_jenkins:1.0
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5
